version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql_db2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  email_sender:
    image: email_sender
    container_name: my_email_sender
    restart: always
    depends_on:
      - mysql  # Ensure MySQL starts before this service
    environment:
      MYSQL_HOST: mysql  # Set the MySQL hostname
      MYSQL_PORT: 3306    # MySQL port

  front_end:
    image: front_end
    container_name: my_front_end
    ports:
      - "80:8000"

  back_end:
    image: back_end
    container_name: my_back_end
    ports:
      - "3000:3000"

volumes:
  mysql-data:
